//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stage_Books.languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stage_Books.languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Stage.
        /// </summary>
        public static string About_Stage {
            get {
                return ResourceManager.GetString("About Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors Categorys.
        /// </summary>
        public static string Authors_Categorys {
            get {
                return ResourceManager.GetString("Authors Categorys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Category.
        /// </summary>
        public static string Book_Category {
            get {
                return ResourceManager.GetString("Book Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Contact.
        /// </summary>
        public static string Book_Contact {
            get {
                return ResourceManager.GetString("Book Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Description.
        /// </summary>
        public static string Book_Description {
            get {
                return ResourceManager.GetString("Book Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book info.
        /// </summary>
        public static string Book_info {
            get {
                return ResourceManager.GetString("Book info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Language.
        /// </summary>
        public static string Book_Language {
            get {
                return ResourceManager.GetString("Book Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Name.
        /// </summary>
        public static string Book_Name {
            get {
                return ResourceManager.GetString("Book Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books Categorys.
        /// </summary>
        public static string Books_Categorys {
            get {
                return ResourceManager.GetString("Books Categorys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books Language.
        /// </summary>
        public static string Books_Language {
            get {
                return ResourceManager.GetString("Books Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books`s Reading.
        /// </summary>
        public static string Books_Reading {
            get {
                return ResourceManager.GetString("Books Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy Right Stage.
        /// </summary>
        public static string copy_Right_Stage {
            get {
                return ResourceManager.GetString("copy Right Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covering.
        /// </summary>
        public static string Covering {
            get {
                return ResourceManager.GetString("Covering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encyclopedia.
        /// </summary>
        public static string Encyclopedia {
            get {
                return ResourceManager.GetString("Encyclopedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fav.
        /// </summary>
        public static string Fav {
            get {
                return ResourceManager.GetString("Fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourit Books.
        /// </summary>
        public static string Favourit_Books {
            get {
                return ResourceManager.GetString("Favourit Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French .
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German .
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail.
        /// </summary>
        public static string Gmail {
            get {
                return ResourceManager.GetString("Gmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        public static string Hindi {
            get {
                return ResourceManager.GetString("Hindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you Catch a Wrong in Text.
        /// </summary>
        public static string if_you_Catch_a_Wrong_in_Text {
            get {
                return ResourceManager.GetString("if you Catch a Wrong in Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Us.
        /// </summary>
        public static string Join_Us {
            get {
                return ResourceManager.GetString("Join Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang of Book.
        /// </summary>
        public static string Lang_of_Book {
            get {
                return ResourceManager.GetString("Lang of Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Read Books.
        /// </summary>
        public static string Most_Read_Books {
            get {
                return ResourceManager.GetString("Most Read Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Favourit.
        /// </summary>
        public static string My_Favourit {
            get {
                return ResourceManager.GetString("My Favourit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        public static string New_Account {
            get {
                return ResourceManager.GetString("New Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Books.
        /// </summary>
        public static string New_Books {
            get {
                return ResourceManager.GetString("New Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note : Please Enter Your Data By English Language.
        /// </summary>
        public static string Note___Please_Enter_Your_Data_By_English_Language {
            get {
                return ResourceManager.GetString("Note : Please Enter Your Data By English Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note : Please Enter Your Data By English Note : Please Enter Your Data By English Language.
        /// </summary>
        public static string Note___Please_Enter_Your_Data_By_English_Note___Please_Enter_Your_Data_By_English_Language {
            get {
                return ResourceManager.GetString("Note : Please Enter Your Data By English Note : Please Enter Your Data By English" +
                        " Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or Create New acount.
        /// </summary>
        public static string or_Create_New_acount {
            get {
                return ResourceManager.GetString("or Create New acount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Visit us On.
        /// </summary>
        public static string Or_Visit_us_On {
            get {
                return ResourceManager.GetString("Or Visit us On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Message.
        /// </summary>
        public static string Our_Message {
            get {
                return ResourceManager.GetString("Our Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Policy.
        /// </summary>
        public static string Our_Policy {
            get {
                return ResourceManager.GetString("Our Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string Our_Services {
            get {
                return ResourceManager.GetString("Our Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Date.
        /// </summary>
        public static string Publishing_Date {
            get {
                return ResourceManager.GetString("Publishing Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Num.
        /// </summary>
        public static string Publishing_Num {
            get {
                return ResourceManager.GetString("Publishing Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Book.
        /// </summary>
        public static string Read_Book {
            get {
                return ResourceManager.GetString("Read Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string Read_More {
            get {
                return ResourceManager.GetString("Read More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reat Book.
        /// </summary>
        public static string Reat_Book {
            get {
                return ResourceManager.GetString("Reat Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Books.
        /// </summary>
        public static string Related_Books {
            get {
                return ResourceManager.GetString("Related Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Book.
        /// </summary>
        public static string Save_Book {
            get {
                return ResourceManager.GetString("Save Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For Any Word in Book.
        /// </summary>
        public static string Search_For_Any_Word_in_Book {
            get {
                return ResourceManager.GetString("Search For Any Word in Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string Search_Results {
            get {
                return ResourceManager.GetString("Search Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results Area.
        /// </summary>
        public static string Search_Results_Area {
            get {
                return ResourceManager.GetString("Search Results Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Topics.
        /// </summary>
        public static string Services_Topics {
            get {
                return ResourceManager.GetString("Services Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Sign_In {
            get {
                return ResourceManager.GetString("Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanich .
        /// </summary>
        public static string Spanich {
            get {
                return ResourceManager.GetString("Spanich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject ofBook.
        /// </summary>
        public static string Subject_ofBook {
            get {
                return ResourceManager.GetString("Subject ofBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suggestions.
        /// </summary>
        public static string suggestions {
            get {
                return ResourceManager.GetString("suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Titel {
            get {
                return ResourceManager.GetString("Titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Authors.
        /// </summary>
        public static string To_Authors {
            get {
                return ResourceManager.GetString("To Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Publishers.
        /// </summary>
        public static string To_Publishers {
            get {
                return ResourceManager.GetString("To Publishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Stege on Facebook.
        /// </summary>
        public static string Visit_Stege_on_Facebook {
            get {
                return ResourceManager.GetString("Visit Stege on Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Stege on Twitter.
        /// </summary>
        public static string Visit_Stege_on_Twitter {
            get {
                return ResourceManager.GetString("Visit Stege on Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string Visitors {
            get {
                return ResourceManager.GetString("Visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What About STAGE.
        /// </summary>
        public static string What_About_STAGE {
            get {
                return ResourceManager.GetString("What About STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Contact Us , Ask About Anything And We Responce on Your E-Mail Address.
        /// </summary>
        public static string You_Can_Contact_Us___Ask_About_Anything_And_We_Responce_on_Your_E_Mail_Address {
            get {
                return ResourceManager.GetString("You Can Contact Us , Ask About Anything And We Responce on Your E-Mail Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your_Save.
        /// </summary>
        public static string Your_Save {
            get {
                return ResourceManager.GetString("Your_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
    }
}
